volumes:
  minio_data:

services:
  movies_admin:
    build:
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/movies_admin/:/usr/src/app/
    ports:
      - "1337:8000"
    env_file:
      - ./envs/env.dev
  movies_film_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./envs/env.dev
  movies_person_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./envs/env.dev
  movies_genre_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./envs/env.dev
  movies_async_api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./envs/env.dev
  movies_auth:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ./envs/env.dev
  elasticsearch:
    ports:
      - "9200:9200"
    env_file:
      - ./envs/env.dev
  postgres:
    env_file:
      - ./envs/env.dev
  redis:
    ports:
      - "6379:6379"
    env_file:
      - ./envs/env.dev
  postgres_auth:
    ports:
      - "5433:5432"
    env_file:
      - ./envs/env.dev
  redis_auth:
    ports:
      - "6380:6379"
    env_file:
      - ./envs/env.dev
  nginx:
    build: ./services/nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - movies_admin
      - movies_async_api
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: movies_jaeger
    ports:
      - "6831:6831"
      - "16686:16686"
  postgres_billing:
    ports:
      - "5434:5432"
    env_file:
      - ./envs/.env.dev
  rabbit_billing:
    ports:
      - "5672:5672"
    env_file:
      - ./envs/.env.dev
  movies_billing_api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./envs/.env.dev
  movies_billing_admin:
    build:
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/movies_billing/admin_panel:/usr/src/app/
    ports:
      - "8002:8000"
    env_file:
      - ./envs/.env.dev
  movies_streaming_admin:
    build:
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/movies_streaming_admin/:/usr/src/app/
    ports:
      - "1338:8000"
    env_file:
      - ./envs/.env.streaming.dev
  movies_streaming_converter_api:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - minio_data:/usr/src/app/data
    ports:
      - "8001:8000"
    env_file:
      - ./envs/.env.streaming.dev
  minio:
    image: minio/minio:RELEASE.2022-04-01T03-41-39Z
    command: server /data --console-address ":9001"
    container_name: minio
    restart: always
    volumes:
      - minio_data:/data
    env_file:
      - ./envs/.env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
  airflow_scheduler:
    env_file:
      - ./envs/.env.streaming.dev
  airflow_worker:
    env_file:
      - ./envs/.env.streaming.dev
  airflow:
    ports:
      - "9002:8080"
    env_file:
      - ./envs/.env.streaming.dev

